name: Dizi Botunu Calistir

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu cek
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Kur
        run: |
          pip install selenium webdriver-manager cloudscraper

      - name: Botu Calistir
        run: python bot.py

      - name: Dosyayi Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: dizi-listesi
          path: canlidizi_listesi.m3u
